# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoQuote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeoQuote

  target 'GeoQuoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GeoQuote-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeoQuote-tvOS

  target 'GeoQuote-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
